### ISSUE TITLE
Is maintenance stopped

### ISSUE THREAD

**Issue by hyahm** [google/goexpect#47]
It's almost a year since it was updated

**Comment by skalle** [comment]
Hi hyahm@. 

It might look like it's stopped but no, I do still watch this project and work on issues.
I've had fairly limited time for a while so haven't been able to work a lot on adding features. 

If/when that changes there's a bunch of things I'd like to get in there.
- Already have an addon where changes to devices can be described in protobufs, this with things like , waiting , re-trying and chaining things together .. Makes it easier to build up libraries of common operations. 
- Multi platform support.. With other terminal libraries out that handle multiple  platforms expect could change over to one of those and get the multiplatform for free. 
- Re-factor, this project was written quite a while ago, both my way to code and Go best practices has changed since , would be nice to get the code up to current standards. 

PRs are always welcome of-course.
